name: Update ReaPack index

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  index:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install reapack-index
        run: gem install reapack-index
      
      - name: Install pandoc
        run: apt install pandoc

      - name: Build index
        run: reapack-index --commit --scan

      - name: Push index
        run: git push
